spring:
  flyway:
    enabled: ${MIGRATION_ENABLE}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      dialect: ${DATABASE_DIALECT}
      connection:
        driver_class: ${DB_DRIVER_CLASS}
      ddl-auto: ${DDL_AUTO}
      show_sql: true

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLE}
    resolve-schema-properties: ${RESOLVE_SCHEMA_PROPERTIES}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED}
  default-produces-media-type: ${DEFAULT_PRODUCES_MEDIA_TYPE}
  writer-with-default-pretty-printer: ${WRITER_WITH_DEFAULT_PRETTY_PRINTER}

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}