spring:
  flyway:
    enabled: ${MIGRATION_ENABLE}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password:

  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      dialect: ${DATABASE_DIALECT}
      connection:
        driver_class: ${DB_DRIVER_CLASS}
      ddl-auto: ${DDL_AUTO}
      show_sql: true

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLE}
    resolve-schema-properties: ${RESOLVE_SCHEMA_PROPERTIES}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED}
  default-produces-media-type: ${DEFAULT_PRODUCES_MEDIA_TYPE}
  writer-with-default-pretty-printer: ${WRITER_WITH_DEFAULT_PRETTY_PRINTER}


logging:
  level:
    root: warn
    org:
      springframework:
        web: error
        hibernate: error
  file:
    name: application.log
    max-size: 1MB
    max-history: 10
    pattern: LOG_DATEFORMAT_PATTERN




security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}